apiVersion: pg.percona.com/v1
kind: PerconaPGCluster
metadata:
  annotations:
    current-primary: pg-oib
  labels:
    crunchy-pgha-scope: pg-oib
    deployment-name: pg-oib
    name: pg-oib
    pg-cluster: pg-oib
    pgo-version: 1.1.0
    pgouser: admin
  name: pg-oib
spec:
#  secretsName: pg-oib-users
#  sslCA: pg-oib-ssl-ca
#  sslSecretName: pg-oib-ssl-keypair
#  sslReplicationSecretName: pg-oib-ssl-keypair
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: disabled
    schedule: "0 4 * * *"
  database: pgdb
  port: "5432"
  user: pguser
  disableAutofail: false
  tlsOnly: false
  standby: false
  pause: false
  keepData: true
  keepBackups: true
#  pgDataSource:
#    restoreFrom: ""
#    restoreOpts: ""
#  tablespaceStorages:
#    lake:
#      volumeSpec:
#        size: 1G
#        accessmode: ReadWriteOnce
#        storagetype: dynamic
#        storageclass: ""
#        matchLabels: ""
#  walStorage:
#    volumeSpec:
#      size: 1G
#      accessmode: ReadWriteOnce
#      storagetype: dynamic
#      storageclass: ""
#      matchLabels: ""
  userLabels:
    pgo-version: "1.1.0"
  pgPrimary:
    image: percona/percona-postgresql-operator:1.1.0-ppg14-postgres-ha
    resources:
      requests:
#      memory: "128Mi"
    tolerations: []
    volumeSpec:
      size: 1G
      accessmode: ReadWriteOnce
      storagetype: dynamic
      storageclass: ""
#      matchLabels: ""
    expose:
      serviceType: ClusterIP
#      loadBalancerSourceRanges:
#      annotations:
#        pg-cluster-annot: pg-oib
#      labels:
#        pg-cluster-label: pg-oib
#    customconfig: ""
  pmm:
    enabled: false
    image: percona/pmm-client:2.24.0
    serverHost: monitoring-service
    serverUser: admin
    pmmSecret: pg-oib-pmm-secret
    resources:
      requests:
#      memory: 200M
#      cpu: 500m
#      limits:
#        cpu: "1"
#        memory: "400M"
  backup:
    image: percona/percona-postgresql-operator:1.1.0-ppg14-pgbackrest
    backrestRepoImage: percona/percona-postgresql-operator:1.1.0-ppg14-pgbackrest-repo
    resources:
      requests:
#      memory: "48Mi"
#      limits:
#        cpu: "1"
#        memory: "64Mi"
    volumeSpec:
      size: 1G
      accessmode: ReadWriteOnce
      storagetype: dynamic
      storageclass: ""
#      matchLabels: ""
#    storages:
#      my-gcs:
#        type: gcs
#        bucket: some-gcs-bucket
#    repoPath: ""
    schedule:
#      - name: "sat-night-backup"
#        schedule: "0 0 * * 6"
#        keep: 3
#        type: full
#        storage: local
      - name: "every-night-backup"
        schedule: "0 0 * * *"
        keep: 2
        type: full
        storage: local
      - name: "hourtly-backup"
        schedule: "45 * * * *"
        keep: 2
        type: incr
        storage: local
  pgBouncer:
    image: percona/percona-postgresql-operator:1.1.0-ppg14-pgbouncer
    size: 1
    resources:
      requests:
#      cpu: "1"
#      memory: "128Mi"
      limits:
#      cpu: "2"
#      memory: "512Mi"
    expose:
      serviceType: ClusterIP
#      loadBalancerSourceRanges:
#      annotations:
#        pg-cluster-annot: pg-oib
#      labels:
#        pg-cluster-label: pg-oib
  pgReplicas:
    hotStandby:
      size: 1
      resources:
        requests:
#          cpu: "1"
#      memory: "128Mi"
#        limits:
#          cpu: "1"
#          memory: "128Mi"
      volumeSpec:
        accessmode: ReadWriteOnce
        size: 1G
        storagetype: dynamic
        storageclass: ""
#        matchLabels: ""
#      affinity:
#        default: null
#      labels:
#        pg-cluster-label: pg-oib
#      annotations:
#        pg-cluster-annot: pg-oib-1
      enableSyncStandby: false
      expose:
        serviceType: ClusterIP
#        loadBalancerSourceRanges:
#        annotations:
#          pg-cluster-annot: pg-oib
#        labels:
#          pg-cluster-label: pg-oib
  pgBadger:
    enabled: false
    image: percona/percona-postgresql-operator:1.1.0-ppg14-pgbadger
    port: 10000
#  securityContext:
#    fsGroup: 1001
#    supplementalGroups: [1001, 1002, 1003]
