---
bootstrap:
  dcs:
    postgresql:
      parameters:
        max_connections: 120
        shared_buffers: 204MB
        effective_cache_size: 820MB
        checkpoint_completion_target: 0.9
        wal_buffers: 7864kB
        effective_io_concurrency: 2
        work_mem: 655kB
        min_wal_size: 1GB
        max_wal_size: 4GB

postgresql:
  pg_hba:
  - local all postgres peer
  - host replication primaryuser 0.0.0.0/0 md5
  - host all primaryuser 0.0.0.0/0 reject
  - host pgdb dev_user 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5

